version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8123:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "5001:5001"
    command: python app.py --port=5001
